### ISSUE TITLE
Logging out and in of a map adds more tiles to purchase

### ISSUE THREAD

**Issue by kurowi35** [algernon-A/FiveTwentyNineTilesLite#1]
Hey there, noticed a bug while saving->quitting to menu-> loading save.

Game version is 1.0.18f1, BepInEx 5.4.22 and FiveTwentyNineTilesLite 1.1.1

Settings in game are "Allocate extra tiles to milestones" and "Select initial starting tiles"

![image](https://github.com/algernon-A/FiveTwentyNineTilesLite/assets/142305490/89890067-0e88-4fa3-b415-ffe2a93124df)

As seen in first screenshot, fresh from booted up game, i am out of tiles to purchase. (21 purchased in total 9 from base, 4+5 from first milestones so im already off...)

Loading the game back 4 times and i now have 10 tiles to purchase : 
![image](https://github.com/algernon-A/FiveTwentyNineTilesLite/assets/142305490/904a5b59-f34a-49fc-9488-4e753cced633)

it then goes 14-16 and seems to cap there. Quitting to desktop and then reloading seems to clear it back to 0.

**Comment by algernon-A** [comment]
Thanks for the report - confirmed.  Obviously the immediate workaround is to not do that, but I'll work on a proper fix.

**Comment by algernon-A** [comment]
Fixed in 1.2.1.  Please check to see that the issue has been resolved, and close this if it has.

**Comment by kurowi35** [comment]
Thanks for the quick fix, working as expected now.
