### ISSUE TITLE
[Request] Add Russian language on Crowdin

### ISSUE THREAD

**Issue by BrokVid** [algernon-A/FiveTwentyNineTilesLite#2]
I don't know why it's not there, but whatever the reason, it's primarily a tool for the game that shouldn't be a way to hamstring some nation.

Besides, Russian is officially present in the game.

I don't want to offend anyone and will help translate this and your other mods for CS2.

P.S. to avoid opening issues in other repositories: add Russian to the other mods for CS2 as well

**Comment by algernon-A** [comment]
Russian was not there simply because I had no requests and no existing translators; there's no politics or anything involved.  Added now.
